source "https://rubygems.org"

gem "jekyll", "~> 4.2.2"
gem "bundler", "~> 2.2"
gem "jekyll-feed", "~> 0.12"
gem "jekyll-seo-tag", "~> 2.6"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-paginate", "~> 1.1"
gem "csv", "~> 3.1"
gem "base64", "~> 0.1"
gem "bigdecimal", "~> 3.1"
gem "minima", "~> 2.5" # Add this line for the minima theme
